// <auto-generated />
namespace ICARUS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190328__ContainerMeta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190328__ContainerMeta));
        
        string IMigrationMetadata.Id
        {
            get { return "201903281514380_2019-03-28__ContainerMeta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
