// <auto-generated />
namespace ICARUS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180718__001ImageGallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180718__001ImageGallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201807180506454_20180718__001-ImageGallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
