// <auto-generated />
namespace ICARUS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180215__003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180215__003));
        
        string IMigrationMetadata.Id
        {
            get { return "201802160451324_2018-02-15__003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
