// <auto-generated />
namespace ICARUS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180718__004FormPostLabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180718__004FormPostLabel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807190042211_20180718__004-FormPost-Label"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
