USE [master]
GO
ALTER DATABASE [ICARUS] SET  OFFLINE
GO

BACKUP LOG [ICARUS] 
TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.ICARUS\MSSQL\Backup\ICARUS_LogBackup_2018-05-25_15-43-21.bak' 
WITH NOFORMAT, NOINIT,  NAME = N'ICARUS_LogBackup_2018-05-25_15-43-21', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5

RESTORE DATABASE [ICARUS] 
FROM  DISK = N'Z:\_BACKUP\_ICARUSDB\ICARUS_2018-05-25.bak' 
WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5

GO


