SELECT TOP 30 * FROM [ICARUS].[ICARUS].[AspNetUserLogins]
SELECT TOP 30 * FROM [ICARUS].[ICARUS].[AspNetRoles]
SELECT TOP 30 * FROM [ICARUS].[ICARUS].[AspNetUserRoles]
SELECT TOP 30 * FROM [ICARUS].[ICARUS].[AspNetUsers]